### PR TITLE
Last message read

### PR DESCRIPTION
**Pull request by moxxiq**
Last commit details

### CODE REVIEW

**Comment by moxxiq** [comment]
Need to handle `Bad Request` on wrong credentials or absence of refresh token

**Comment by moxxiq** [comment]
File sending issues

**Comment by moxxiq** [comment]
> File sending issues

Fixed

**Review by TheBestTvarynka — APPROVED** [review]
It seems like all works)
:cake:

**Comment by moxxiq** [comment]
> It seems like all works)
> cake

OK, I believe you

**Review by moxxiq — COMMENTED** [review]
All Good!

**Pull request merged**
